### ISSUE TITLE
cant read feature id with `[id]`

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-carto-libs#22]
I am creating an openmaptiles layer with that query
```yaml
datasource:
    geometry_field: geometry
    key_field: osm_id
    key_field_as_attribute: no
    srid: 900913
    query: (SELECT osm_id, geometry, class, network, name, ref, symbol, textcolor, color, ascent, descent, distance, description, website, extent FROM layer_route(!bbox!, z(!scale_denominator!))) AS t
```

So the feature `id` is the `osm_id`. Now i need to read that `id` through css style to test for selection.
However this does not seem possible. `[id]` does not return the id. Could we add that?
