### ISSUE TITLE
`Line` text can be upside down with `text-allow-overlap`

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-carto-libs#35]
if you have something like this in your css
```less
[class='waypointline'] {
			line-color: #00000077;
			line-join: round;
			line-cap: round;
			line-width: 3;
			text-name: [text];
			text-placement: line;
			text-wrap-before: true;
			text-face-name: @mont;
			text-size: 10;
			text-allow-overlap: true;
			text-halo-fill: @route_label_halo;
			text-halo-radius: @route_label_halo_radius;
			text-dy: @route_text_dy;
		}
```
depending on the line "order" the text is upside down. If you set `text-allow-overlap: false;` the text will always be drawn correctly
